
# EJERCICIO 2
import math

#ENTRADA
R = float(input("escribe el valor del radio del circulo:"))
#Proceso
Perimetro = math.pi *R*2
Area= math.pi *R**2

#salida

print ("El perimetro es",Perimetro)
print ("El área es",Area)

# EJERCICIO 3

# import datetime
# #ENTRADA

# FECHA_ACTUAL = datetime.datetime.now()
# date = FECHA_ACTUAL.date()
# AÑO_ACTUAL= date.year
# AÑO_NACIMIENTO=2000


# #PROCESO

# EDAD= (AÑO_ACTUAL-AÑO_NACIMIENTO)

# #SALIDA
# print ("La edad es",EDAD)

# EJERCICIO 4

#ENTRADA


# GRADOS= 100   
# MAGNITUD = "F"

# # PROCESO
# if MAGNITUD == "C":
#     K = GRADOS + 273.15
#     F = ((9 * GRADOS) / 5) + 32
# elif MAGNITUD == "K":
#     KC = GRADOS - 273.15
#     KF = ((9 * (GRADOS - 273.15) / 5) + 32)
#     print(GRADOS, MAGNITUD, " EQUIVALEN A", KC, "°C") 
#     print(GRADOS, MAGNITUD, " EQUIVALEN A", KF, "°F")
# elif MAGNITUD == "F":
#     FC = (5 * (GRADOS - 32) / 9)
#     FK = (5 * (GRADOS - 32) / 9) + 273.15
#     print(GRADOS, MAGNITUD, " EQUIVALEN A", FC,"°C") 
#     print(GRADOS, MAGNITUD, " EQUIVALEN A", FK,"°K")
# else:
#     print("MAGNITUD no es una unidad válida")

# # SALIDA
#     print(GRADOS, MAGNITUD, " EQUIVALEN A", K,"°K") 
#     print(GRADOS, MAGNITUD, " EQUIVALEN A", F,"°F")

#EJERCICIO 5

